// <auto-generated />
using System;
using UpRestEye3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace UpRestEye3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EyeRestWAs.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierBankAccount")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierTaxNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmountExclTaxes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmountInclTaxes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EyeRestWAs.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ExternalPriceExclTaxes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExternalPriceInclTaxes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExternalTaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalTaxCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InternalPriceExclTaxes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InternalPriceInclTaxes")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalProductCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InternalTaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalTaxCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EyeRestWAs.Models.TaxCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("TaxCategories");
                });

            modelBuilder.Entity("EyeRestWAs.Models.Product", b =>
                {
                    b.HasOne("EyeRestWAs.Models.Invoice", null)
                        .WithMany("Products")
                        .HasForeignKey("InvoiceId");
                });

            modelBuilder.Entity("EyeRestWAs.Models.TaxCategory", b =>
                {
                    b.HasOne("EyeRestWAs.Models.Invoice", null)
                        .WithMany("TaxCategories")
                        .HasForeignKey("InvoiceId");
                });

            modelBuilder.Entity("EyeRestWAs.Models.Invoice", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("TaxCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
